export const productCategories = [
  { slug: "icu-products", title: "ICU Products", short: "Critical-care essentials selected for demanding clinical environments.", intro: "A focused range of branded products supporting intensive-care and critical-care workflows.", focus: ["Critical-care consumables", "Patient-care accessories", "Clinical workflow support"] },
  { slug: "disinfectants", title: "Disinfectants", short: "Professional infection-prevention and surface hygiene solutions.", intro: "Professional products selected to support effective infection-prevention protocols across healthcare settings.", focus: ["Surface disinfection", "Clinical hygiene", "Institutional infection control"] },
  { slug: "protective-clothing", title: "Protective Clothing", short: "Clinical apparel and barriers designed to support safer working.", intro: "Protective apparel and barrier solutions for healthcare professionals and controlled clinical environments.", focus: ["Clinical protective wear", "Barrier protection", "Institutional requirements"] },
  { slug: "dialysis", title: "Dialysis", short: "Dependable products supporting renal-care workflows.", intro: "Specialised branded products supporting dialysis centres, renal-care teams and associated clinical workflows.", focus: ["Renal-care products", "Dialysis workflow support", "Institutional supply"] },
  { slug: "hernia", title: "Hernia", short: "Specialised surgical products for hernia-management procedures.", intro: "A specialised portfolio developed around the product requirements of hernia-management procedures.", focus: ["Specialised surgical products", "Procedure-focused support", "Clinical enquiries"] },
  { slug: "breast-prosthesis", title: "Breast Prosthesis", short: "Thoughtfully selected post-operative and prosthetic-care solutions.", intro: "Thoughtfully selected prosthetic and post-operative solutions supported by sensitive, informed service.", focus: ["Breast prosthesis", "Post-operative support", "Product guidance"] },
  { slug: "allied-products", title: "Allied Products", short: "A practical range of complementary surgical and medical supplies.", intro: "Complementary surgical and medical products that extend Astra Sales' focused clinical portfolio.", focus: ["Surgical accessories", "Medical consumables", "Complementary products"] },
];
export const mainNav = [["Home", "/"], ["Products", "/products"], ["About", "/about"], ["Partners", "/partners"], ["Careers", "/careers"], ["Contact", "/contact"]] as const;
